config/routes.rb
Rails.application.routes.draw do
  get 'news/index' => "news#index" , as: :news_index
  post 'news/vote/:id' => "news#vote" , as: :news_vote 
  post 'news/devote/:id' => "news#devote" , as: :news_devote 

  root "news#index"

end

app/models/article.rb
class Article < ActiveRecord::Base
	has_attached_file :avatar,  default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  	@data = Article.all ;
  	
  end

  def vote
  	@id = params[:id] ;
  	@x = Article.find(params[:id]) ;
  	@x.votes+=1 ;
  	@x.save

  
  end

  def devote
  	@id = params[:id] ;
  	@x = Article.find(params[:id]) ;
  	@x.votes-=1 ;
  	@x.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hackbvp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 	
 	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'components/test', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-noty/2.4.1/packaged/jquery.noty.packaged.min.js"></script>
  <script type="text/javascript" src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
  <%= csrf_meta_tags %>

</head>
<body>

<div id="upper" class="fbclass">
	<span class="logo">	SMART-AI </span>
</div>

<%= yield %>

</body>
</html>

app/views/news/devote.js.erb
$("#votes<%= @id %>").html(function(index,text){
	 return parseInt(text)-1 ;
	

}) ;

$("#yes-no<%= @id %>").stopImmediatePropagation() ;

$("#yes-no<%= @id %>").remove() ;
//$("#parent").append("<div id='page_number'> You are watching 5th object out of 100 </div>");

//$("outer<%= @id %>").prepend("<div> You are watching 5th object out of 100 </div>");


// alert("VOTE SUBMITTED !! ")

noty({
	text: 'VOTE SUBMITTED !!',
	type: 'success',
	timeout: 2000
});

app/views/news/index.html.erb
<form id="contactForm1" action="http://192.168.43.210:5000/getconf" method="GET">
    <!-- Form input fields here (do not forget your name attributes). -->
    POST NEWS HERE KNOW AI RESULT :<br><input type="text" name="headline"> 

    <input type="submit" name="submit">
</form>

<div id="mynews"> 

</div>


<h1>#Trending news</h1>

<% @data.each do |i| %>


<div id="title"> 
<%= i.title %>
</div>
<br>
<div id="outer" >
<div id="image">
<%= image_tag i.avatar_file_name %>
</div>

<div id="description">
<%= i.description %>
</div>



</div>
<div id="yes-no<%= i.id %>" class="r_ir_class" >
	<span> Please give your answer : </span>
	<span id="yes">

	<%= link_to "RELEVANT NEWS",  news_vote_path(i.id) , id: "yes#{i.id}" , remote: true , method: :post %>
	</span>
	&nbsp; &nbsp; &nbsp; &nbsp; 
	<span id="no">
		<%= link_to "IRRELEVANT NEWS",  news_devote_path(i.id) , remote: true , method: :post %>
	</span>

</div>



<div id="votes_id">
VOTES :
<span id="votes<%= i.id %>" style="color: white ; background-color: red "> 
<%= i.votes %> 
</span>
</div>

<br> 
<br>
<br> 
<br>

<% end %>

<script type="text/javascript">
    var frm = $('#contactForm1');

    frm.submit(function (e) {

        e.preventDefault();

       var x = $.ajax({
        url: 'http://192.168.43.210:5000/getconf',
        type: 'GET',
        data: frm.serialize() , 
        success: function (response) {
            alert(response) ;
            window.location = news_index_path ;
        },
        error: function () {
            alert("error");
        }, crossdomain: true ,
    }); 

    var parsed_data = JSON.parse(x.responseText); 

    $('#mynews').html(parsed_data.maxconflink) ;


</script>

<script type="text/javascript">
    var frm = $('#contactForm1');

    frm.submit(function (e) {

        e.preventDefault();

       var x = $.ajax({
        url: 'http://192.168.43.210:5000/getconf',
        type: 'GET',
        data: frm.serialize() , 
        async: false ,
        success: function (response) {
            alert("hiiiiii") ;
            // window.location.href = dat.redirect ;
        },
        error: function () {
            alert("error") ;
        }, 
    }); 

    var parsed_data = JSON.parse(x.responseText); 

    $('#mynews').html(parsed_data.maxconflink) ;


</script>

app/views/news/vote.js.erb
$("#votes<%= @id %>").html(function(index,text){
	 return parseInt(text)+(1) ;
	

}) ;

//$("#yes-no<%= @id %>").stopImmediatePropagation() ;

$("#yes-no<%= @id %>").remove() ;
//$("#parent").append("<div id='page_number'> You are watching 5th object out of 100 </div>");

//$("outer<%= @id %>").prepend("<div> You are watching 5th object out of 100 </div>");


// alert("VOTE SUBMITTED !! ")

noty({
	text: 'VOTE SUBMITTED !!',
	type: 'success',
	timeout: 2000
});